
export const volData = [
        {
          id: 1,
          vol: "TU724",
          imageVol: img01,
          compagnie: "Tunisair",
          destination: "Paris Orly",
          typeVoyage: "Aller-retour",
          dateRecherche: "2025-07-09T17:20:00Z",
          dateDepart: "2025-07-30T09:00:00Z",
          dateArrivee: "2025-08-06T18:00:00Z",
          lieuDepart: "Tunis Carthage (Tunisie)",
          lieuArrivee: "Aéroport Paris Orly (France)",
          statutVol: "À l'heure",
          aeroportDepart: "Tunis Carthage",
          icon: <FaPlaneDeparture />,
          recommendation: true,
          rating: 3.8,
        },
        {
          id: 2,
          vol: "AF101",
          imageVol: img02,
          compagnie: "Air France",
          destination: "Bamako",
          typeVoyage: "Humanitaire / étudiant",
          dateRecherche: "2025-07-09T17:22:00Z",
          dateDepart: "2025-07-30T06:30:00Z",
          dateArrivee: "2025-08-30T08:00:00Z",
          lieuDepart: "Nice Côte d’Azur (France)",
          lieuArrivee: "Aéroport International Modibo Keïta (Mali)",
          statutVol: "Retardé",
          aeroportDepart: "Nice Côte d’Azur",
          icon: <PiStudent />,
          recommendation: true,
          rating: 4.8,
        },
        {
          id: 3,
          vol: "LH303",
          imageVol: img03,
          compagnie: "Lufthansa",
          destination: "Berlin",
          typeVoyage: "Voyage touristique",
          dateRecherche: "2025-07-09T17:25:00Z",
          dateDepart: "2025-07-30T12:00:00Z",
          dateArrivee: "2025-08-04T14:30:00Z",
          lieuDepart: "Tunis Carthage (Tunisie)",
          lieuArrivee: "Berlin Brandenburg Airport (Allemagne)",
          statutVol: "Enregistrement en cours",
          aeroportDepart: "Tunis Carthage",
          icon: <FaBiking />,
          recommendation: false,
          rating: 4.0,
        },
        {
          id: 4,
          vol: "ET901",
          imageVol: img04,
          compagnie: "Ethiopian Airlines",
          destination: "Addis-Abeba",
          typeVoyage: "Voyage touristique",
          dateRecherche: "2025-07-09T17:28:00Z",
          dateDepart: "2025-07-30T07:45:00Z",
          dateArrivee: "2025-08-07T11:00:00Z",
          lieuDepart: "Tunis Carthage (Tunisie)",
          lieuArrivee: "Bole International Airport (Éthiopie)",
          statutVol: "À l’heure",
          aeroportDepart: "Tunis Carthage",
          icon: <FaBiking />,
          recommendation: true,
          rating: 4.2,
        },
        {
          id: 5,
          vol: "QR445",
          imageVol: img05,
          compagnie: "Qatar Airways",
          destination: "Doha",
          typeVoyage: "Voyage VIP / Premium",
          dateRecherche: "2025-07-09T17:31:00Z",
          dateDepart: "2025-07-30T20:00:00Z",
          dateArrivee: "2025-07-30T23:45:00Z",
          lieuDepart: "Tunis Carthage (Tunisie)",
          lieuArrivee: "Hamad International Airport (Qatar)",
          statutVol: "Confirmé",
          aeroportDepart: "Tunis Carthage",
          icon: <FaPlaneDeparture />,
          recommendation: true,
          rating: 4.9,
        },
    ]

const VolsCard = () => {
  
}